# Generated by Django 5.0.4 on 2025-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryprofile',
            name='profile_image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS81CHVRX7-8gRLhhfJ8nJFk2FlOV4gLxabHQ&s', upload_to='profile_pics'),
        ),
    ]
