# Generated by Django 5.0.4 on 2025-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_award_country_rank_personnel_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
