# Generated by Django 5.0.4 on 2025-03-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_award_url_country_url_personnel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
