# Generated by Django 5.0.4 on 2025-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_personnel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='years_of_service',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
