# Generated by Django 5.0.4 on 2025-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_personnel_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
