# Generated by Django 5.0.4 on 2025-03-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
